.PHONY: verilog

verilog:
	-@ echo "WARNING: This command requires the sv2v package to be installed on your system."
	-@ echo "I'm not sure what happens if you run it without sv2v installed. If you haven't installed it already, install it now."
	-@ echo ""
	-@ rm -rf v/*
	sv2v *.sv -w ./v/
